import Joi from "joi";

// Schema for a single item inside the section_content array
const contentItemSchema = Joi.object({
  // content_id is generated by backend if missing, but allowed if updating
  content_id: Joi.string().optional(),

  title: Joi.string()
    .required()
    .messages({ "string.empty": "Content title is required" }),
  type: Joi.string().valid("video", "reading", "quiz", "task").required(),

  // Specific fields based on your requirements
  video_url: Joi.string().uri().optional().allow("", null),
  video_duration: Joi.number().integer().min(0).optional(),
  description: Joi.string().optional().allow("", null),

  reading_content: Joi.string().optional().allow("", null),

  quiz_id: Joi.number().integer().optional().allow(null), // Optional link
  task_details: Joi.string().optional().allow("", null),

  is_free_preview: Joi.boolean().optional().default(false),
});

export const courseSectionSchema = Joi.object({
  course_id: Joi.number().integer().required(),
  section_title: Joi.string().min(3).max(255).required(),
  section_order: Joi.number().integer().required(),

  // The Array of Section Content
  section_content: Joi.array().items(contentItemSchema).default([]),
});

export const updateSectionSchema = Joi.object({
  section_title: Joi.string().min(3).max(255).optional(),
  section_order: Joi.number().integer().optional(),
  section_content: Joi.array().items(contentItemSchema).optional(),
});
